module.exports = [
  { name: '01d', file: require('../../../images/sun.png') },
  { name: '01n', file: require('../../../images/sun.png') },
  { name: '02d', file: require('../../../images/cloud.png') },
  { name: '02n', file: require('../../../images/cloud.png') },
  { name: '03d', file: require('../../../images/cloud.png') },
  { name: '03n', file: require('../../../images/cloud.png') },
  { name: '04d', file: require('../../../images/cloud.png') },
  { name: '04n', file: require('../../../images/cloud.png') },
  { name: '09d', file: require('../../../images/rain.png') },
  { name: '09n', file: require('../../../images/rain.png') },
  { name: '10d', file: require('../../../images/rain.png') },
  { name: '10n', file: require('../../../images/rain.png') },
  { name: '11d', file: require('../../../images/thunder.png') },
  { name: '11n', file: require('../../../images/thunder.png') },
  { name: '13d', file: require('../../../images/snow.png') },
  { name: '13n', file: require('../../../images/snow.png') },
  { name: '50d', file: require('../../../images/mist.png') },
  { name: '50n', file: require('../../../images/mist.png') },
];
