module.exports = [
  {
    i: 'sun',
    name: '01d',
    file: '../../images/sun.png',
    colorOne: '#F6D365',
    colorTwo: '#FDA085',
    colorIcon: '#F6D365',
  },
  {
    i: 'sun',
    name: '01n',
    file: '../../images/sun.png',
    colorOne: '#F6D365',
    colorTwo: '#FDA085',
    colorIcon: '#F6D365',
  },
  {
    i: 'cloud-sun',
    name: '02d',
    file: '../../images/cloud.png',
    colorOne: '#A1C4FD',
    colorTwo: '#C2E9FB',
    colorIcon: '#A1C4FD',
  },
  {
    i: 'cloud-sun',
    name: '02n',
    file: '../../images/cloud.png',
    colorOne: '#A1C4FD',
    colorTwo: '#C2E9FB',
    colorIcon: '#A1C4FD',
  },
  {
    i: 'cloud',
    name: '03d',
    file: '../../images/cloud.png',
    colorOne: '#A1C4FD',
    colorTwo: '#C2E9FB',
    colorIcon: '#A1C4FD',
  },
  {
    i: 'cloud',
    name: '03n',
    file: '../../images/cloud.png',
    colorOne: '#A1C4FD',
    colorTwo: '#C2E9FB',
    colorIcon: '#A1C4FD',
  },
  {
    i: 'cloud',
    name: '04d',
    file: '../../images/cloud.png',
    colorOne: '#A1C4FD',
    colorTwo: '#C2E9FB',
    colorIcon: '#A1C4FD',
  },
  {
    i: 'cloud',
    name: '04n',
    file: '../../images/cloud.png',
    colorOne: '#A1C4FD',
    colorTwo: '#C2E9FB',
    colorIcon: '#A1C4FD',
  },
  {
    i: 'cloud-showers-heavy',
    name: '09d',
    file: '../../images/rain.png',
    colorOne: '#CFD9DF',
    colorTwo: '#E2EBF0',
    colorIcon: '#CFD9DF',
  },
  {
    i: 'cloud-showers-heavy',
    name: '09n',
    file: '../../images/rain.png',
    colorOne: '#CFD9DF',
    colorTwo: '#E2EBF0',
    colorIcon: '#9b9b9b',
  },
  {
    i: 'cloud-sun-rain',
    name: '10d',
    file: '../../images/rain.png',
    colorOne: '#CFD9DF',
    colorTwo: '#E2EBF0',
    colorIcon: '#9b9b9b',
  },
  {
    i: 'cloud-sun-rain',
    name: '10n',
    file: '../../images/rain.png',
    colorOne: '#CFD9DF',
    colorTwo: '#E2EBF0',
    colorIcon: '#9b9b9b',
  },
  {
    i: 'thunder-cloud',
    name: '11d',
    file: '../../images/thunder.png',
    colorOne: '#5B75A3',
    colorTwo: '#446280',
    colorIcon: '#7a9dbf',
  },
  {
    i: 'thunder-cloud',
    name: '11n',
    file: '../../images/thunder.png',
    colorOne: '#5B75A3',
    colorTwo: '#446280',
    colorIcon: '#7a9dbf',
  },
  {
    i: 'snowflake',
    name: '13d',
    file: '../../images/snow.png',
    colorOne: '#e6e9f0',
    colorTwo: '#eef1f5',
    colorIcon: '#a4abb2',
  },
  {
    i: 'snowflake',
    name: '13n',
    file: '../../images/snow.png',
    colorOne: '#e6e9f0',
    colorTwo: '#eef1f5',
    colorIcon: '#a4abb2',
  },
  {
    i: 'wind',
    name: '50d',
    file: '../../images/wind.png',
    colorOne: '#ACCBEE',
    colorTwo: '#E7F0FD',
    colorIcon: '#ACCBEE',
  },
  {
    i: 'wind',
    name: '50n',
    file: '../../images/wind.png',
    colorOne: '#ACCBEE',
    colorTwo: '#E7F0FD',
    colorIcon: '#ACCBEE',
  },
];
